# main reference for public anisette servers: https://github.com/SideStore/anisette-servers/blob/main/servers.json
# (app will also try to dynamically fetch these from github when user goes to settings page)
defaultAnisetteUrl=https://ani.sidestore.io
developerWebsite=https://wander.dev
projectGithub=https://github.com/parawanderer/OpenTagViewer
projectWiki=https://github.com/parawanderer/OpenTagViewer/wiki
# Linked from the AMap API key dialog, since users have to register their own key
amapWikiPage=https://github.com/parawanderer/OpenTagViewer/wiki/%5BMaps%5D-How-To:-Use-AMap-(%E9%AB%98%E5%BE%B7%E5%9C%B0%E5%9B%BE)
