package dev.wander.android.opentagviewer;

import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.TooltipCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.databinding.DataBindingUtil;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.android.material.imageview.ShapeableImageView;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import dev.wander.android.opentagviewer.databinding.ActivityInformationBinding;
import dev.wander.android.opentagviewer.ui.compat.WindowPaddingUtil;
import dev.wander.android.opentagviewer.ui.widget.FlowLayout;
import dev.wander.android.opentagviewer.util.android.PropertiesUtil;
import dev.wander.android.opentagviewer.util.android.WebLink;

public class InformationActivity extends AppCompatActivity {
    private static final String TAG = InformationActivity.class.getSimpleName();

    /** Both generated by scripts/fetch_contributors.py; see the workflow that runs it. */
    private static final String CONTRIBUTORS_ASSET = "contributors.json";
    private static final String AVATAR_ASSET_DIR = "contributors";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ActivityInformationBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_information);
        WindowPaddingUtil.insetForSystemBars(binding.getRoot());
        binding.setHandleClickBack(this::finish);

        if (this.getSupportActionBar() != null) {
            this.getSupportActionBar().hide();
        }

        try {
            TextView version = findViewById(R.id.appVersion);
            var info = getPackageManager().getPackageInfo(getPackageName(), 0);
            var filledVersionString = String.format(
                    getResources().getString(R.string.version_x),
                    info.versionName
            );
            version.setText(filledVersionString);

        } catch (PackageManager.NameNotFoundException e) {
            throw new RuntimeException(e);
        }

        this.showContributors();

        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });
    }

    /**
     * Fills the avatar grid from the list bundled at build time.
     * <br>
     * Read from assets rather than fetched, which is what
     * {@code scripts/fetch_contributors.py} exists for. Calling the GitHub API here would be
     * rate limited in practice - it allows 60 requests an hour per IP, and carrier-grade NAT
     * puts a great many users behind each one - and it would hand every user's IP to GitHub
     * on opening a screen that shows no remote content otherwise.
     */
    private void showContributors() {
        FlowLayout grid = findViewById(R.id.contributors_flow);
        if (grid == null) {
            return;
        }

        final List<Contributor> contributors = readContributors();
        if (contributors.isEmpty()) {
            // Nothing to show, so give the space back to the rest of the page.
            findViewById(R.id.contributors_scroll).setVisibility(View.GONE);
            return;
        }

        final LayoutInflater inflater = getLayoutInflater();

        for (Contributor contributor : contributors) {
            ShapeableImageView avatar = (ShapeableImageView)
                    inflater.inflate(R.layout.contributor_avatar, grid, false);

            Bitmap bitmap = readAvatar(contributor.avatar);
            if (bitmap == null) {
                // The manifest and the images are generated together, so this only happens if
                // one of them was edited by hand. Skip rather than show an empty circle.
                Log.w(TAG, "No bundled avatar for " + contributor.login + "; skipping");
                continue;
            }
            avatar.setImageBitmap(bitmap);
            avatar.setContentDescription(contributor.login);

            // Long press rather than a tooltip attribute: works below API 26 too.
            TooltipCompat.setTooltipText(avatar, contributor.login);

            avatar.setOnClickListener(v -> openUrl(contributor.profileUrl));

            grid.addView(avatar);
        }
    }

    private List<Contributor> readContributors() {
        try (InputStream in = getAssets().open(CONTRIBUTORS_ASSET)) {
            ContributorsFile parsed = new ObjectMapper()
                    .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
                    .readValue(in, ContributorsFile.class);

            return parsed.contributors == null ? List.of() : parsed.contributors;
        } catch (IOException e) {
            Log.w(TAG, "Could not read " + CONTRIBUTORS_ASSET, e);
            return List.of();
        }
    }

    private Bitmap readAvatar(final String filename) {
        if (filename == null || filename.isBlank()) {
            return null;
        }

        try (InputStream in = getAssets().open(AVATAR_ASSET_DIR + "/" + filename)) {
            return BitmapFactory.decodeStream(in);
        } catch (IOException e) {
            Log.w(TAG, "Could not read avatar " + filename, e);
            return null;
        }
    }

    private void openUrl(final String url) {
        WebLink.open(this, url);
    }

    /** Shape of assets/contributors.json. */
    public static class ContributorsFile {
        public List<Contributor> contributors;
    }

    public static class Contributor {
        public String login;
        public String profileUrl;
        public String avatar;
        public int commits;
    }



    public void onClickWiki(View view) {
        Log.d(TAG, "Clicked App Wiki button");

        var properties = PropertiesUtil.getProperties(this.getAssets(), "app.properties");
        assert properties != null;
        WebLink.open(this, properties.getProperty("projectWiki"));
    }

    public void onClickGithub(View view) {
        Log.d(TAG, "Clicked Github button");

        var properties = PropertiesUtil.getProperties(this.getAssets(), "app.properties");
        assert properties != null;
        WebLink.open(this, properties.getProperty("projectGithub"));
    }
}