package dev.wander.android.opentagviewer.python.icloud;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * What a completed join produced, and what has to outlive the process to use it.
 *
 * <p><b>The keys inside {@link #getPeerJson()} are the only copy in existence.</b> Lose them and
 * this app's peer is stranded on the user's account - unusable, and not removable from here
 * either. So this is stored before anything else is allowed to go wrong, and it is stored
 * encrypted: FindMy.py serialises a circle member's private keys in the clear, and says so.
 *
 * <p>Two independent ways back, and neither substitutes for the other:
 *
 * <ul>
 *   <li>{@link #getPeerJson()} is how an ordinary refresh reads the keychain with no passcode.
 *       This is the point of having joined.</li>
 *   <li>{@link #getEntropy()} with {@link #getEscrowPasscode()} recovers the same peer
 *       <i>through escrow</i>, which is the way back if this app's encrypted store is ever
 *       destroyed but the account still holds the record.</li>
 * </ul>
 */
@Getter
@AllArgsConstructor
public class KeychainMembership {

    /**
     * The membership itself: a peer id and two private keys, as FindMy.py serialises them.
     *
     * <p>Opaque here on purpose. This app has no business parsing a circle member's keys; it
     * stores what it was given and hands the same bytes back.
     */
    private final String peerJson;

    /** The bottle's entropy, base64. The escrow route's half of the recovery. */
    private final String entropy;

    /**
     * The passcode this app's own escrow record was enrolled under.
     *
     * <p>Generated by {@link EscrowPasscode}, 256 bits, and never shown to anybody - the user has
     * no use for it and could not act on it. Kept solely so the escrow route above is available.
     */
    private final String escrowPasscode;

    /** The record's label, which is how §7.1's deletion addresses it. */
    private final String label;

    /**
     * How many view keys were re-addressed to this peer when it joined.
     *
     * <p>Worth keeping for a log rather than for logic: a join reporting zero is a join that
     * technically succeeded and bought nothing, and that is the sort of thing only visible in
     * hindsight when somebody reports that fetching stopped working.
     */
    private final int shares;
}
