package dev.wander.android.opentagviewer.anisette;

import android.content.Context;
import android.util.Log;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Locale;

/**
 * What the app expects to receive from Apple's CDN, and the check that it did.
 *
 * <p>Backed by {@code assets/adi-libraries.json}, regenerated by
 * {@code scripts/update_adi_stub_symbols.py} alongside the stub symbol lists - the two are
 * taken from the same download, so they can never describe different builds.
 *
 * <p>Verifying matters for two separate reasons. The libraries are downloaded at runtime over
 * the network, and they are then executed in this process; a hash check is the difference
 * between that and trusting whatever arrives. And Apple can replace the APK at any time, in
 * which case the obfuscated symbol names may have moved and the stub lists may be incomplete -
 * a mismatch here catches that before anything is loaded, rather than as a crash inside
 * Apple's code.
 */
public final class AdiLibraryManifest {
    private static final String TAG = "AdiLibraryManifest";

    private static final String ASSET = "adi-libraries.json";

    private final JsonNode root;

    private AdiLibraryManifest(JsonNode root) {
        this.root = root;
    }

    public static AdiLibraryManifest load(Context context) throws IOException {
        try (InputStream stream = context.getAssets().open(ASSET)) {
            return new AdiLibraryManifest(new ObjectMapper().readTree(stream));
        }
    }

    /** The Apple Music build these hashes came from, for logs and error messages. */
    public String apkVersion() {
        final JsonNode apk = this.root.get("apk");
        return apk == null || apk.get("version") == null ? "unknown" : apk.get("version").asText();
    }

    /** Where to fetch from. Kept in the manifest so the source can move without a code change. */
    public String url() {
        return this.root.get("url").asText();
    }

    /**
     * Check one downloaded library against its recorded digest.
     *
     * @return null if it matches, otherwise a description of how it differs
     */
    public String verify(File library, String abi) {
        final JsonNode expected = this.root.path("libraries").path(abi).path(library.getName());
        if (expected.isMissingNode()) {
            return library.getName() + " is not listed in " + ASSET + " for " + abi;
        }

        final long expectedSize = expected.path("size").asLong();
        if (library.length() != expectedSize) {
            return String.format(Locale.ROOT, "%s is %d bytes, expected %d",
                    library.getName(), library.length(), expectedSize);
        }

        final String actual;
        try {
            actual = sha256(library);
        } catch (final IOException | NoSuchAlgorithmException e) {
            return "could not hash " + library.getName() + ": " + e.getMessage();
        }

        final String expectedHash = expected.path("sha256").asText();
        if (!actual.equalsIgnoreCase(expectedHash)) {
            return library.getName() + " hashes to " + actual + ", expected " + expectedHash
                    + " - Apple has probably shipped a new Apple Music build (this manifest is "
                    + "from " + apkVersion() + ")";
        }

        Log.d(TAG, library.getName() + " matches the manifest");
        return null;
    }

    private static String sha256(File file) throws IOException, NoSuchAlgorithmException {
        final MessageDigest digest = MessageDigest.getInstance("SHA-256");

        try (FileInputStream in = new FileInputStream(file)) {
            final byte[] buffer = new byte[64 * 1024];
            int read;
            while ((read = in.read(buffer)) != -1) {
                digest.update(buffer, 0, read);
            }
        }

        final StringBuilder out = new StringBuilder(64);
        for (final byte b : digest.digest()) {
            out.append(String.format("%02x", b));
        }
        return out.toString();
    }
}
