# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: MacOS Exporter App

on:
  release:
    types: published

env:
  PYTHONPATH: "${{ github.workspace }}/python:$PYTHONPATH"
  PYINSTALLER_PYTHON_VER: 3.13
  APP_NAME: OpenTagViewer-ExportWizardMacOS

jobs:
  test-release-version:
    runs-on: macos-14

    # Only run this for 'macos-exporter-v<whatever>' tags!
    if: |
      github.event_name == 'release'
      && (github.event.release.prerelease == true || github.event.release.published_at != null)
      && startsWith(github.event.release.tag_name, 'macos-exporter-v')

    steps: # (reuses steps from full flow!)
    - name: Checkout code
      uses: actions/checkout@v4

    # Do everything strictly for the python version used in the release build...
    - name: Set up Python ${{ env.PYINSTALLER_PYTHON_VER }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYINSTALLER_PYTHON_VER }}

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt

    - name: Lint with flake8
      working-directory: . # run flake8 from repository root
      run: |
        # Run flake8 on the 'python' directory, letting it pick up the .flake8 config file
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./python --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./python --count --exit-zero --statistics

    - name: Test with pytest
      working-directory: ./python
      run: |
        pytest ./test

  build-apple-silicon:
    needs: test-release-version
    uses: ./.github/workflows/macos-exporter-common.yml
    with:
      os-version: macos-14 # Apple Silicon

  build-intel:
    needs: test-release-version
    uses: ./.github/workflows/macos-exporter-common.yml
    with:
      os-version: macos-13 # Intel (these runners seem scarcely available for some reason)